Reg.exe add "HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\StartupApproved\Run" /v "Spotify" /t REG_BINARY /d "0300000070E93D7B5A46D901" /f 

timeout /t 1 /nobreak > NUL

del "%HOMEPATH%\appdata\Roaming\Spotify\Apps\concert.spa" /F /Q  
del "%HOMEPATH%\appdata\Roaming\Spotify\Apps\concerts.spa" /F /Q  
del "%HOMEPATH%\appdata\Roaming\Spotify\Apps\error.spa" /F /Q  
del "%HOMEPATH%\appdata\Roaming\Spotify\Apps\findfriends.spa" /F /Q  
del "%HOMEPATH%\appdata\Roaming\Spotify\Apps\show.spa" /F /Q  
del "%HOMEPATH%\appdata\Roaming\Spotify\Apps\station.spa" /F /Q  
del "%HOMEPATH%\appdata\Roaming\Spotify\Apps\stations.spa" /F /Q  
timeout /t 1 /nobreak > NUL
del "%appdata%\Spotify\locales\am.pak" /F /Q  
del "%appdata%\Spotify\locales\ar.mo" /F /Q  
del "%appdata%\Spotify\locales\ar.pak" /F /Q  
del "%appdata%\Spotify\locales\bg.pak" /F /Q  
del "%appdata%\Spotify\locales\bn.pak" /F /Q  
del "%appdata%\Spotify\locales\ca.pak" /F /Q  
del "%appdata%\Spotify\locales\cs.mo" /F /Q  
del "%appdata%\Spotify\locales\cs.pak" /F /Q  
del "%appdata%\Spotify\locales\da.pak" /F /Q  
del "%appdata%\Spotify\locales\de.mo" /F /Q  
del "%appdata%\Spotify\locales\de.pak" /F /Q  
del "%appdata%\Spotify\locales\el.mo" /F /Q  
del "%appdata%\Spotify\locales\el.pak" /F /Q  
del "%appdata%\Spotify\locales\es.mo" /F /Q  
del "%appdata%\Spotify\locales\es.pak" /F /Q  
del "%appdata%\Spotify\locales\es-419.mo" /F /Q  
del "%appdata%\Spotify\locales\es-419.pak" /F /Q  
del "%appdata%\Spotify\locales\et.pak" /F /Q  
del "%appdata%\Spotify\locales\fa.pak" /F /Q  
del "%appdata%\Spotify\locales\fi.mo" /F /Q  
del "%appdata%\Spotify\locales\fi.pak" /F /Q  
del "%appdata%\Spotify\locales\fil.pak" /F /Q  
del "%appdata%\Spotify\locales\fr.mo" /F /Q  
del "%appdata%\Spotify\locales\fr.pak" /F /Q  
del "%appdata%\Spotify\locales\fr-CA.mo" /F /Q  
del "%appdata%\Spotify\locales\gu.pak" /F /Q  
del "%appdata%\Spotify\locales\he.mo" /F /Q  
del "%appdata%\Spotify\locales\he.pak" /F /Q  
del "%appdata%\Spotify\locales\hi.pak" /F /Q  
del "%appdata%\Spotify\locales\hr.pak" /F /Q  
del "%appdata%\Spotify\locales\hu.mo" /F /Q  
del "%appdata%\Spotify\locales\hu.pak" /F /Q  
del "%appdata%\Spotify\locales\id.mo" /F /Q  
del "%appdata%\Spotify\locales\id.pak" /F /Q  
del "%appdata%\Spotify\locales\it.mo" /F /Q  
del "%appdata%\Spotify\locales\it.pak" /F /Q  
del "%appdata%\Spotify\locales\ja.mo" /F /Q  
del "%appdata%\Spotify\locales\ja.pak" /F /Q  
del "%appdata%\Spotify\locales\kn.pak" /F /Q  
del "%appdata%\Spotify\locales\ko.mo" /F /Q  
del "%appdata%\Spotify\locales\ko.pak" /F /Q  
del "%appdata%\Spotify\locales\lt.pak" /F /Q  
del "%appdata%\Spotify\locales\lv.pak" /F /Q  
del "%appdata%\Spotify\locales\ml.pak" /F /Q  
del "%appdata%\Spotify\locales\mr.pak" /F /Q  
del "%appdata%\Spotify\locales\ms.mo" /F /Q  
del "%appdata%\Spotify\locales\ms.pak" /F /Q  
del "%appdata%\Spotify\locales\nb.pak" /F /Q  
del "%appdata%\Spotify\locales\nl.mo" /F /Q  
del "%appdata%\Spotify\locales\nl.pak" /F /Q  
del "%appdata%\Spotify\locales\pl.mo" /F /Q  
del "%appdata%\Spotify\locales\pl.pak" /F /Q  
del "%appdata%\Spotify\locales\pt-BR.mo" /F /Q  
del "%appdata%\Spotify\locales\pt-BR.pak" /F /Q  
del "%appdata%\Spotify\locales\pt-PT.pak" /F /Q  
del "%appdata%\Spotify\locales\ro.pak" /F /Q  
del "%appdata%\Spotify\locales\ru.mo" /F /Q  
del "%appdata%\Spotify\locales\ru.pak" /F /Q  
del "%appdata%\Spotify\locales\sk.pak" /F /Q  
del "%appdata%\Spotify\locales\sl.pak" /F /Q  
del "%appdata%\Spotify\locales\sr.pak" /F /Q  
del "%appdata%\Spotify\locales\sv.mo" /F /Q  
del "%appdata%\Spotify\locales\sv.pak" /F /Q  
del "%appdata%\Spotify\locales\sw.pak" /F /Q  
del "%appdata%\Spotify\locales\ta.pak" /F /Q  
del "%appdata%\Spotify\locales\te.pak" /F /Q  
del "%appdata%\Spotify\locales\th.mo" /F /Q  
del "%appdata%\Spotify\locales\th.pak" /F /Q  
del "%appdata%\Spotify\locales\tr.mo" /F /Q  
del "%appdata%\Spotify\locales\tr.pak" /F /Q  
del "%appdata%\Spotify\locales\uk.pak" /F /Q  
del "%appdata%\Spotify\locales\vi.mo" /F /Q  
del "%appdata%\Spotify\locales\vi.pak" /F /Q  
del "%appdata%\Spotify\locales\zh-CN.pak" /F /Q  
del "%appdata%\Spotify\locales\zh-Hant.mo" /F /Q  
del "%appdata%\Spotify\locales\zh-TW.pak" /F /Q  
