cd "%~dp0"
DevManView.exe /disable "UMBus Root Bus Enumerator"
DevManView.exe /disable "Root Print Queue"
DevManView.exe /disable "NDIS Virtual Network Adapter Enumerator"
DevManView.exe /disable "Microsoft Virtual Drive Enumerator"
DevManView.exe /disable "Microsoft Hyper-V Virtualization Infrastructure Driver"
DevManView.exe /disable "Microsoft GS Wavetable Synth"
DevManView.exe /disable "Microsoft Device Association Root Enumerator"
DevManView.exe /disable "Composite Bus Enumerator"
DevManView.exe /disable "Microsoft UEFI-Compliant System"
DevManView.exe /disable "System board"
DevManView.exe /disable "SM Bus Controller"
DevManView.exe /disable "Motherboard resources"
DevManView.exe /disable "PCI Encryption/Decryption Controller"
DevManView.exe /disable "Microsoft Windows Management Interface for ACPI"
DevManView.exe /disable "High precision event timer"
DevManView.exe /disable "Base System Device"
DevManView.exe /disable "PCI Data Acquisition and Signal Processing Controller"
DevManView.exe /disable "PCI Simple Communications Controller"
DevManView.exe /disable "PCI Device"
DevManView.exe /disable "Unknown Device"
DevManView.exe /disable "PCI Memory Controller"
DevManView.exe /disable "PCI standard RAM Controller"
DevManView.exe /disable "ACPI Processor Aggregator"
DevManView.exe /disable "ACPI Wake Alarm"
DevManView.exe /disable "System Speaker"
DevManView.exe /disable "System Timer"
DevManView.exe /disable "WAN Miniport (IKEv2)"
DevManView.exe /disable "WAN Miniport (IP)"
DevManView.exe /disable "WAN Miniport (IPv6)"
DevManView.exe /disable "WAN Miniport (L2TP)"
DevManView.exe /disable "WAN Miniport (Network Monitor)"
DevManView.exe /disable "WAN Miniport (PPPOE)"
DevManView.exe /disable "WAN Miniport (PPTP)"
DevManView.exe /disable "WAN Miniport (SSTP)"
DevManView.exe /disable "Programmable Interrupt Controller"
DevManView.exe /disable "Numeric Data Processor"
DevManView.exe /disable "Microsoft Kernel Debug Network Adapter"
DevManView.exe /disable "HID-compliant consumer control device"
DevManView.exe /disable "PCI standard ISA bridge"
DevManView.exe /disable "Plug and Play Software Device Enumerator"
DevManView.exe /disable "Direct memory access controller"
DevManView.exe /disable "WAN Miniport"
DevManView.exe /disable "Teredo Tunneling"
DevManView.exe /disable "Microsoft Kernel Debug Network Adapter"
DevManView.exe /disable "UMBus Root Bus Enumerator"
DevManView.exe /disable "Composite Bus Enumerator"
DevManView.exe /disable "Microsoft Virtual Drive Enumerator"
DevManView.exe /disable "NDIS Virtual Network Adapter Enumerator"
DevManView.exe /disable "System Timer"
DevManView.exe /disable "System Speaker"
DevManView.exe /disable "Programmable Interrupt Controller"
DevManView.exe /disable "PCI standard RAM Controller"
DevManView.exe /disable "PCI Memory Controller"
DevManView.exe /disable "Microsoft Storage Spaces Controller"
DevManView.exe /disable "Microsoft Windows Management Interface for ACPI"
DevManView.exe /disable "Microsoft Wi-Fi Direct Virtual Adapter"
DevManView.exe /disable "Microsoft GS Wavetable Synth"
DevManView.exe /disable "Remote Desktop Device Redirector Bus"
DevManView.exe /disable "SM Bus Controller"
DevManView.exe /disable "AMD PSP"
DevManView.exe /disable "Intel SMBus"
DevManView.exe /disable "Intel Management Engine"
DevManView.exe /disable "AURA LED Controller"
DevManView.exe /disable "PCI Simple Communications Controller"
DevManView.exe /disable "Microsoft System Management BIOS Driver"
DevManView.exe /disable "NVIDIA Virtual Audio Device"
DevManView.exe /disable "Intel(R) Management Engine Interface"
DevManView.exe /disable "Microsoft RRAS Root Enumerator"
DevManView.exe /disable "Microsoft Radio Device Enumeration Bus"








Exit
